name: black
on:
  push:
    branches:
      - main
      - develop
jobs:
  black:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.10
      - run: |
          python -m pip install --upgrade pip 
          pip install -r requirements.txt
      - run: |
          black --check --verbose .